config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [:index, :show, :new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :movie
  belongs_to :list 
 
  # The comment of a bookmark cannot be shorter than 6 characters.
  validates :comment, 
                length: { minimum: 6 }, 
                presence: true

  validates :movie, uniqueness: {scope: :list, message: "already entered, choose another film"}

end
 

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  has_many :movies, through: :bookmarks

  validates :name, 
                uniqueness: true, 
                presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, 
                uniqueness: true, 
                presence: true

  validates :overview,  
                presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: [:new, :create, :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end

  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end

  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%# View Method for bookmark %>

<h1>What is the comment you wish to leave</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Save any kind of movies</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %><li>
  <% end %>
</ul>

<%= link_to 'Create a new list', new_list_url %>

app/views/lists/new.html.erb
<h1>Create a new category</h1>

<%= form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back to Lists', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to 'Back to Lists', lists_path %>

<%= link_to 'Add Bookmark',  new_list_bookmark_path(@list) %>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item">
      <%= bookmark.comment %>
      <%= link_to "Remove comment on for #{bookmark.movie.title}",
                  list_bookmark_path(@list, bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>